courses/udacity_intro_to_tensorflow_for_deep_learning/l01c01_introduction_to_colab_and_python.ipynb

Changes:
* `print("Result from HelloWorld: {}".format(i, r))` => to use `r` only.
* `print("Type of b: {}, type of b[0]: {}".format(type(a), type(a[0])))` => to use variable `b` instead of `a`

Change variable used to comply given example.

---

courses/udacity_intro_to_tensorflow_for_deep_learning/l03c01_classifying_images_of_clothing.ipynb

In the code 128 neurons are created but the description only mentions 126.

Typo: 126 neurons -> 128 neurons

---

lite/examples/gesture_classification/web/index.js
lite/examples/gesture_classification/web/ui.js
lite/examples/gesture_classification/web/webcam.js

Updated apis/methods called in gesture_classification(web) to latest corresponding version because the current code doesn't run as the script link fetches the latest script which includes api structure changes that don't work with this example.

Updated apis/methods called in gesture_classification(web) to latest version.

---

tensorflow_examples/models/pix2pix/pix2pix.py

As per [previous discussion](https://github.com/tensorflow/examples/commit/f28b124a2aabdc58a66f5f12904824fd110599a2#r34756231), the scale parameter of the instance normalization should be initialized with mean `1.0` instead of `0.0`.

Fix instance normalization scale initializer

---

courses/udacity_intro_to_tensorflow_for_deep_learning/l08c03_moving_average.ipynb
courses/udacity_intro_to_tensorflow_for_deep_learning/l08c04_time_windows.ipynb
courses/udacity_intro_to_tensorflow_for_deep_learning/l08c05_forecasting_with_machine_learning.ipynb
courses/udacity_intro_to_tensorflow_for_deep_learning/l08c06_forecasting_with_rnn.ipynb
courses/udacity_intro_to_tensorflow_for_deep_learning/l08c07_forecasting_with_stateful_rnn.ipynb
courses/udacity_intro_to_tensorflow_for_deep_learning/l08c08_forecasting_with_lstm.ipynb
courses/udacity_intro_to_tensorflow_for_deep_learning/l08c09_forecasting_with_cnn.ipynb

Seems like in original version they used `compat.v2` and after it was refactored to tf2, but somehow left broken.
As a result current live version is broken - no import of tensorflow. I removed `enable_v2_behavior` since colab does support tf2 with magic above.
PS: feels like I am the first one checking these notebooks 🙈

Fix issues with not imported tensorflow

---

community/en/docs/deploy/distributed.md

The second column of first row for tf.train.ClusterSpec construction is misplaced, which may lead to some confusion to new users.

Make distributed tensorflow doc work

---

community/en/position_encoding.ipynb

The variable delta (SSE) for the second plot of the Near Position section is undefined, and thus does not produce a plot.

Fixing undefined delta

---

lite/examples/image_classification/android/README.md

"TensorFlow Lite Android image classification example" links to a missing tensorflow.org page and returns a 404 error. The intended resource can be found as a markdown file in this repository and the link has been updated.

Fix broken link in README.md

---

lite/codelabs/digit_classifier/android/finish/app/src/main/java/org/tensorflow/lite/codelabs/digitclassifier/DigitClassifier.kt

Possibly Fixes [#37780](https://github.com/tensorflow/tensorflow/issues/37780).  
I have observed in tensorflow code repo that the doc is built from the docstring in code itself. I assume the same thing is here too. That's why as per my understanding I have changed the code in order to show it in codelab.  
@mihaimaruseac and @MarkDaoust , Please review this one.

Modified spacing and comments in interpreter code in order to show it in codelabs

---

lite/examples/image_classification/ios/ImageClassification.xcodeproj/project.pbxproj
lite/examples/image_classification/ios/RunScripts/download_models.sh
lite/examples/object_detection/ios/ObjectDetection.xcodeproj/project.pbxproj
lite/examples/object_detection/ios/RunScripts/download_models.sh
lite/examples/posenet/ios/PoseNet.xcodeproj/project.pbxproj
lite/examples/speech_commands/ios/RunScripts/download_models.sh
lite/examples/speech_commands/ios/SpeechCommands.xcodeproj/project.pbxproj

`$SRCROOT/RunScripts/download_models.sh` has been changed to `"$SRCROOT/RunScripts/download_models.sh"` (with parentheses) in `project.pbxproj`.
Similarly, in the `download_models.sh` script, fixed a "No such file or directory" error in `cd $SCRIPT_DIR` when a space occurs in `pwd`.
```
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"                                          
cd $SCRIPT_DIR                                                                                  
```
Changing `cd $SCRIPT_DIR ` to `cd "$SCRIPT_DIR"` (with parentheses) fixes this issue.

Fixed bug with spaces in working directory paths

---

lite/examples/digit_classifier/ios/DigitClassifier/Info.plist

Since the `Result Label`'s text color was set to "Default (Label color)", this caused the text to default to white, which is invisible on a white background.
This forces the app to always use Light mode, regardless of the iPhone settings.
**An alternative fix is to set the text color to 'Dark Text Color' or equivalent, but the Storyboard diff would be messier.**
1. In iPhone Settings -> Developer: Set 'Dark Appearance' to true
2. View DigitClassifier app
You will see:
After the fix, you will see:

[DigitClassifier][iOS] Fixed issue where the label is invisible when iPhone is in dark mode

---

lite/examples/image_segmentation/ios/README.md

There's a typo error in [Requirements of README.md](https://github.com/tensorflow/examples/tree/master/lite/examples/image_segmentation/ios#requirements) of `examples/lite/examples/image_segmentation/ios/`
This PR fixes it by changing Simuiator to Simulator.

Fixed a typo error in README.md

---

community/en/flowers_tf_lite.ipynb

The comment mentions binary cross-entropy loss whereas the loss being used is categorical cross entropy

Fix loss typo

---

community/en/flowers_tf_lite.ipynb

Model.fit() in TF2 apparently doesn't check the generator length the way fit_generator() used to in 1.x, so this code would seemingly run forever. Now we need to pass the length as step length for training and validation data.

Fix the training stage for TF2 API

---

lite/examples/digit_classifier/ios/DigitClassifier/DigitClassifier.swift
lite/examples/image_segmentation/ios/ImageSegmentation/ImageSegmentator.swift

Hi,
The `AllocateTensors ()` is executed once at initialization.
- DigitClassifier
https://github.com/tensorflow/examples/blob/master/lite/examples/digit_classifier/ios/DigitClassifier/DigitClassifier.swift#L51
- ImageSegmentator
https://github.com/tensorflow/examples/blob/master/lite/examples/image_segmentation/ios/ImageSegmentation/ImageSegmentator.swift#L126
But there was an unnecessary call to `allocateTensor()` elsewhere, so I removed it.
Thanks.

[iOS] Remove unnecessary allocateTensors()

---

lite/examples/posenet/ios/PoseNet/Extensions/CVPixelBufferExtension.swift
lite/examples/posenet/ios/PoseNet/ModelDataHandler/ModelDataHandler.swift

Remove `byteCount` parameter on `rgbData` method, because not using now.

Remove not using param on iOS posenet's rgbData method

---

lite/examples/object_detection/android/app/src/main/java/org/tensorflow/lite/examples/detection/LegacyCameraConnectionFragment.java

After `onPause` executes, camera will be released and set to be null. If `onResume` executes next, **camera is null and NullPointerException occurs**: `camera.startPreview();`. So we should reopen the camera again.
Reproduce this issue:
1. Open the object detection page.
2. Switch to home page by press home button to trigger the execution of onPause.
3. Switch back to the object detection page to trigger the execution of onResume. Then NullPointerException occurs.
So I think we should move the camera setup operations into one standalone method. Then we can share these operations in these two conditions:
1. Open the camera when SurfaceTexture is ready.
2. Reopen the camera in onResume.

bug fix: NullPointerException occurs in onResume.

---

lite/examples/object_detection/ios/ObjectDetection/Extensions/CVPixelBufferExtension.swift

when selecting image from iPhone gallery, we got ARGB images, this change relax pixel format limit in the preprocess step(CVPixelBuffer::resize()) for supporting such image.

image scale operator should works for different pixel formats, not limited to BGRA

---

lite/examples/speech_commands/android/app/src/main/java/org/tensorflow/lite/examples/speech/RecognizeCommands.java

**Same fix as https://github.com/tensorflow/examples/pull/232 but without unit test coverage** 
Previous logic added a reference to the result array to the Deque (as opposed
to the value of the result array). When a new result was added to the Deque,
all previous results were updated to this value (because they were references)
meaning the averaging operation was performed on a Deque of identical arrays -
effectively just returning the final value added to the Deque, rather than an
average of previous results.
The code change extracts this updating logic to a function which is independently
testable, and modifies the logic to add the array value rather than a reference.

Fix bug in Android speech_commands average score calculation

---

community/en/position_encoding.ipynb

I fixed various typos in the textual description of the notebook.

Fixed typos in position_encoding.ipynb

---

lite/examples/image_classification/ios/README.md

The CD and pod command were not separated. Therefore, step 2 in building resulted in a "Too many parameters" error.

Fixed typo in instructions

---

community/en/transformer_chatbot.ipynb

The code uses MAX_SAMPLES=50000 but the description uses MAX_SAMPLES=25000.
This commit syncs the two, favouring the code as the correct value.

fix: MAX_SAMPLES match description to code

---

lite/examples/object_detection/android/README.md

Removed "and in `TFLiteObjectDetectionAPIModel.java` set `labelOffset` to `0`" from lite/examples/object_detection/android/README.md as this no longer exists in current android java code.
`TFLiteObjectDetectionAPIModel.java` diff from last commit, 
https://github.com/tensorflow/examples/commit/de42482b453de6f7b6488203b20e7eec61ee722e#diff-0cf980453f18b3cc1368f8eb16a803f9

Removed `TFLiteObjectDetectionAPIModel.java` set `labelOffset` to `0` instruction from README

---

lite/examples/image_classification/raspberry_pi/README.md
lite/examples/object_detection/raspberry_pi/README.md

This May, Raspbian was renamed to Raspberry Pi OS, as visible on the [official Raspberry Pi downloads page](https://www.raspberrypi.org/downloads/raspberry-pi-os/). In order to maintain consistency and reduce confusion for new users, we should replace Raspbian with Raspberry Pi OS in our docs wherever it makes sense.
Also see https://github.com/tensorflow/tensorflow/pull/44102 .

Rename Raspbian to Raspberry Pi OS

---

community/en/position_encoding.ipynb

Previous link appears to lead to nowhere
Closes https://github.com/tallamjr/tfexamples/issues/1
modified:   community/en/position_encoding.ipynb

Fix broken link pointing to transformers.ipynb

---

lite/examples/posenet/android/app/src/main/java/org/tensorflow/lite/examples/posenet/CameraActivity.kt
lite/examples/posenet/android/app/src/main/java/org/tensorflow/lite/examples/posenet/PosenetActivity.kt

The backgroundHandler was holding a reference that was preventing native memory from getting cleaned up. The captureCallback implementation was not doing anything so there is no noticeable gain in having a backgroundHandler for captureSession!!.setRepeatingRequest().
It was leaking about 0.3 GB per minute. It is more noticeable when the screen is set to stay on because when the screen goes to sleep the backgroundHanler is released and the memory is cleaned up.  
Setting the setRepeatingRequest callback and handler to null seems to stop the leak.
It is hard to use the profiler because it slows everything down. I left in some commented code I used to monitor the memory while testing.

Keep screen on and fix memory leak in Android Posenet demo

---

CONTRIBUTING.md
README.md

The https://www.tensorflow.org/community/contribute  in `tensorflow/examples/CONTRIBUTING.md`  was  mistyped as https://www.tensorflow.org/community/contributing, thus making it land on a 404 not find web page 
I fixed it

Fixed Broken/Outdated link in   tensorflow/examples/CONTRIBUTING.md

---

lite/examples/digit_classifier/ios/README.md

Update path to reference the digit_classifier directory instead of the image_classification directory.

Fix path in lite/examples/digit_classifier/ios/README.md

---

lite/examples/posenet/ios/PoseNet/Extensions/CVPixelBufferExtension.swift

Condition `abs(rect.size.width / rect.size.height - source.size.width / source.size.height)` checks wrong sizes. It should check size of source against size of destination. But it checks size of self against size of destination which is wrong.
There's confusing shadowing here: `size` as parameter and `size` property of self. It's better to give parameter different name e.g. `destSize`.

Fix condition in posenet example

---

lite/examples/text_classification/ios/README.md

Rightnow we have readme title "Digit Classifier iOS sample" in the text classification IOS sample, I changed that to "TensorFlow Lite text classification iOS sample"

changed readme title of text classification IOS sample

---

README.md

In `tensorflow/examples/README.md`  the hyperlink to `Community examples` was referring to the community folder  which is no longer available thus leading it to land it on a 404 Page Not found web page. I fixed the link with the current updated link i.e `https://devlibrary.withgoogle.com`.

Fixed Broken/Outdated link
