courses/udacity_intro_to_tensorflow_for_deep_learning/l02c01_celsius_to_fahrenheit.ipynb
Thanks for this great course!
(and link to ipynb was off a bit)
=> bug: typo Fahrenheit

courses/udacity_intro_to_tensorflow_for_deep_learning/l02c01_celsius_to_fahrenheit.ipynb
=> Fix typo in Udacity course notebook

courses/udacity_intro_to_tensorflow_for_deep_learning/l02c01_celsius_to_fahrenheit.ipynb
Noticed a couple typos while working through the examples.
=> Fix a couple typos

courses/udacity_intro_to_tensorflow_for_deep_learning/l02c01_celsius_to_fahrenheit.ipynb
Signed-off-by: Marcela Morales Quispe <marcela.morales.quispe@gmail.com>
=> Complete the missing close parenthesis.

courses/udacity_intro_to_tensorflow_for_deep_learning/l02c01_celsius_to_fahrenheit.ipynb
Missing 'i' in line 301 in 'initially'
Changed 'relationshop' to 'relationship' in line 370
=> Fixed typos in l02c01_celsius_to_fahrenheit.ipynb

courses/udacity_intro_to_tensorflow_for_deep_learning/l03c01_classifying_images_of_clothing.ipynb
Signed-off-by: Marcela Morales Quispe <marcela.morales.quispe@gmail.com>
=> Remove a close parenthesis that is not needed.

community/en/nmt_with_luong_attention.ipynb
Add a Jupyter notebook to create and train a Sequence-to-Sequence model with Luong-style attention mechanism.
This is the Jupyter notebook of the source code in my blog post: [Neural Machine Translation With Attention Mechanism](https://machinetalk.org/2019/03/29/neural-machine-translation-with-attention-mechanism/).
This PR was suggested by @random-forests.
=> Add NMT with Luong attention

tensorflow_examples/models/densenet/densenet_distributed_test.py, tensorflow_examples/models/densenet/densenet_test.py
This adds validation to the Densenet examples.
=> Densenet Example: Add validation of accuracy.

courses/udacity_intro_to_tensorflow_for_deep_learning/l01c01_introduction_to_colab_and_python.ipynb, courses/udacity_intro_to_tensorflow_for_deep_learning/l02c01_celsius_to_fahrenheit.ipynb, courses/udacity_intro_to_tensorflow_for_deep_learning/l03c01_classifying_images_of_clothing.ipynb, courses/udacity_intro_to_tensorflow_for_deep_learning/l04c01_image_classification_with_cnns.ipynb, courses/udacity_intro_to_tensorflow_for_deep_learning/l05c01_dogs_vs_cats_without_augmentation.ipynb, courses/udacity_intro_to_tensorflow_for_deep_learning/l05c02_dogs_vs_cats_with_augmentation.ipynb, courses/udacity_intro_to_tensorflow_for_deep_learning/l05c03_exercise_flowers_with_data_augmentation.ipynb, courses/udacity_intro_to_tensorflow_for_deep_learning/l05c04_exercise_flowers_with_data_augmentation_solution.ipynb, courses/udacity_intro_to_tensorflow_for_deep_learning/l06c01_tensorflow_hub_and_transfer_learning.ipynb, courses/udacity_intro_to_tensorflow_for_deep_learning/l06c02_exercise_flowers_with_transfer_learning.ipynb, courses/udacity_intro_to_tensorflow_for_deep_learning/l06c03_exercise_flowers_with_transfer_learning_solution.ipynb
Fixed a few typos here and there, fixed source link in [this ](https://github.com/tensorflow/examples/blob/master/courses/udacity_intro_to_tensorflow_for_deep_learning/l05c01_dogs_vs_cats_without_augmentation.ipynb)lesson and added better output in a few places.
I would like to discuss a few things:
1. In [two ](https://github.com/tensorflow/examples/blob/master/courses/udacity_intro_to_tensorflow_for_deep_learning/l05c01_dogs_vs_cats_without_augmentation.ipynb)[notebooks ](https://github.com/tensorflow/examples/blob/master/courses/udacity_intro_to_tensorflow_for_deep_learning/l05c02_dogs_vs_cats_with_augmentation.ipynb)there's this line _"For the TensorFlow imports, we directly specify Keras symbols (Sequential, Dense, etc.). This enables us to refer to these names directly in our code …
=> small fixes in Udacity Intro to TensorFlow

lite/examples/posenet/android/README.md
Changed it from `tensorflow-lite` to `lite`.
=> Update the example path.

community/en/hyperparamter_search.ipynb
- Notebook showcasing hyperparameter tuning with Keras-Tuner
- Compatible with Tensorflow 2.0 RC
- Follows all the recommended guidelines and best practices from Google I/O 19
=> Keras-Tuner Notebook

community/en/tensorboard/tbdev_getting_started.ipynb
Add a getting started notebook for TensorBoard.dev.
=> Add getting started notebook for TensorBoard.dev

community/en/position_encoding.ipynb
it seems that delta variable is now named SSE
=> fix variable name error

courses/udacity_intro_to_tensorflow_for_deep_learning/l04c01_image_classification_with_cnns.ipynb
In the notebook it said that the prediction is correct. i think it is due to a copy past from the feed forward notebook
=> preddiction for the first test image is incorrect

courses/udacity_intro_to_tensorflow_for_deep_learning/l02c01_celsius_to_fahrenheit.ipynb, courses/udacity_intro_to_tensorflow_lite/tflite_c05_exercise_rock_paper_scissors.ipynb
=> Minor comment fixes

courses/udacity_intro_to_tensorflow_for_deep_learning/l07c01_saving_and_loading_models.ipynb
Fixes: https://github.com/tensorflow/tensorflow/issues/35616
=> Fixed the typo

lite/examples/gesture_classification/ml/tensorflowjs_to_tflite_colab_notebook.ipynb
Tensorflow and Keras now have the same version as in requierments.txt file
=> Tensorflow and Keras versions update

courses/udacity_intro_to_tensorflow_lite/tflite_c05_exercise_rock_paper_scissors.ipynb, courses/udacity_intro_to_tensorflow_lite/tflite_c06_exercise_rock_paper_scissors_solution.ipynb
Fixes: https://github.com/tensorflow/tensorflow/issues/35940
=> Replaced cats_vs_dogs with rock_paper_scissors in exercise

courses/udacity_intro_to_tensorflow_for_deep_learning/l03c01_classifying_images_of_clothing.ipynb, courses/udacity_intro_to_tensorflow_for_deep_learning/l04c01_image_classification_with_cnns.ipynb
Added cache() to optimize training time.
=> Optimize training time

community/en/nmt_with_luong_attention.ipynb
Remove `%tensorflow_version` and `from __future__` in nmt_with_luong_attention.ipynb
=> Remove `%tensorflow_version` and `from __future__`

community/en/nn_from_scratch.ipynb
Colab button fixed.
While merging this PR this issue will automatically close, fixes: https://github.com/tensorflow/tensorflow/issues/38017
=> Button fix 1

community/en/Tensorflow_Datasets_Example.ipynb
Added a comprehensive guide to use Tensorflow Dataset colab example
=> Added Tensorflow Dataset example

courses/udacity_intro_to_tensorflow_lite/tflite_c04_exercise_convert_model_to_tflite_solution.ipynb
The line "`splits = tfds.Split.ALL.subsplit(weighted=(80, 10, 10))`" was causing "`**AssertionError: Unrecognized instruction format: NamedSplitAll()(tfds.percent[0:80])**`" during `tfds.load()`.
Issue is fixed by using "`split=['train[:80%]', 'train[80%:90%]', 'train[90%:]`"
=> Fixed assertion error during tfds subsplit()

courses/udacity_intro_to_tensorflow_for_deep_learning/l08c05_forecasting_with_machine_learning.ipynb
Changed 20 to 30 in the description.
=> Wrong Window Size while training the model #35728

lite/examples/object_detection/android/app/src/main/java/org/tensorflow/lite/examples/detection/tflite/TFLiteObjectDetectionAPIModel.java
You need to use the number of detections from the output and not the NUM_DETECTONS variable declared on top because on some models, they don't always output the same total number of detections
For example, your model's NUM_DETECTIONS = 20, but sometimes it only outputs 16 predictions
If you don't use the output's numDetections, you'll get nonsensical data
=> Use output's numDetections instead of static NUM_DETECTIONS

lite/examples/image_classification/raspberry_pi/README.md, lite/examples/object_detection/raspberry_pi/README.md
I corrected a couple typos in Raspberry Pi TFLite examples.
=> Fix a couple typos in TFLite examples

community/en/flowers_tf_lite.ipynb
Forgot to include the fix for this second training stage in cl#210.
=> Fix the second training stage

lite/examples/bert_qa/ios/ViewInSwiftUI/Info.plist, lite/examples/bert_qa/ios/ViewInUIKit/Info.plist, lite/examples/image_classification/ios/ImageClassification/Info.plist, lite/examples/image_segmentation/ios/ImageSegmentation/Info.plist, lite/examples/object_detection/ios/ObjectDetection/Info.plist, lite/examples/speech_commands/ios/SpeechCommands/Info.plist, lite/examples/style_transfer/ios/StyleTransfer/Info.plist
Hi,
I run iOS app in the dark mode, some text and button are hidden.
So, I disabled the dark mode appearance in some iOS.
Thanks.
---
Screenshots when a problem occurs.
Bert QA
Image Classification
Image Segmentation
Object Detection
Speech Commands
Style Transfer
=> Disable dark mode appearance of iOS apps.

lite/examples/bert_qa/ios/.gitignore, lite/examples/bert_qa/ios/BertQA.xcodeproj/project.pbxproj
Hi,
- Fix project tree
- Add gitignore for download files
Thanks.
=> Update iOS Bert QA project setting

courses/udacity_intro_to_tensorflow_for_deep_learning/l03c01_classifying_images_of_clothing.ipynb, courses/udacity_intro_to_tensorflow_for_deep_learning/l04c01_image_classification_with_cnns.ipynb
As I was working on the course, I noticed the output is not as expected - sums up to 1. This is how it's fixed
=> Fixed forgotten activation function

lite/examples/object_detection/ios/ObjectDetection.xcodeproj/project.pbxproj, lite/examples/object_detection/ios/ObjectDetection/ModelDataHandler/ModelDataHandler.swift, lite/examples/object_detection/ios/Podfile.lock
Hi,
I update Object Detection project.
- Add Pofile.lock and Pod setting to pbxproj
- Upgrade Swift version 4.2 to 5
Thanks.
=> Update iOS Object Detection project setting

lite/examples/object_detection/android/app/src/main/java/org/tensorflow/lite/examples/detection/tflite/TFLiteObjectDetectionAPIModel.java, lite/examples/object_detection/ios/ObjectDetection/ModelDataHandler/ModelDataHandler.swift
fix ios example preprocessing for floating model per discuss in #40442
=> object detection ios example - correct preprocessing logic for floating model

community/en/text_classification_solution.ipynb
This is the solution for the multiclass exercise of the new text classification tutorial on tensorflow.org
=> multiclass text classification solution

lite/tools/build_model_maker_api_docs.py
Here's an api-reference generator for model maker, based off the one for tf.lite.
Here's the TOC it generates, does this look right:
```
toc:
- title: tflite_model_maker
section:
- title: Overview
path: /tflite_model_maker
- title: tflite_model_maker.compat
section:
- title: Overview
path: /tflite_model_maker/compat
- title: get_tf_behavior
path: /tflite_model_maker/compat/get_tf_behavior
- title: setup_tf_behavior
path: /tflite_model_maker/compat/setup_tf_behavior
- title: tflite_model_maker.configs
section:
- title: Overview
path: /tflite_model_maker/configs
- title: QuantizationConfig
path: /tflite_model_maker/configs/QuantizationConfig
- title: tflite_model_maker.image_classifier
section:
- title: Overview
path: /tflite_model_maker/image_classifier
- title: create
path: …
```
=> Add api-docs generator script for model_maker

lite/examples/object_detection/ios/ObjectDetection/Camera Feed/CameraFeedManager.swift, lite/examples/object_detection/ios/ObjectDetection/ModelDataHandler/ModelDataHandler.swift, lite/examples/object_detection/ios/ObjectDetection/ViewControllers/ViewController.swift
Fixed some spelling mistakes to improve the code readability.
=> Fix typos in iOS object detection example code

courses/udacity_intro_to_tensorflow_for_deep_learning/l03c01_classifying_images_of_clothing.ipynb
Instead of explicitly setting the class names, get them from the Dataset metadata.
=> Get class names from Dataset metadata

community/en/a3c_blogpost/README.md, community/en/a3c_blogpost/a3c_cartpole.py
tensorflow/models@9f901e086a9e9b5f5f26a0e2ad0e3891e7871890
=> Copy a3c blogpost from tensorflow/models

lite/examples/image_classification/android/lib_support/src/main/java/org/tensorflow/lite/examples/classification/tflite/Classifier.java
Added GPU Compatibility check (introduced since 2.3.0) to TensorFlow Support example.
=> Add GPU Compatibility check

lite/examples/model_personalization/transfer_learning/requirements.txt, lite/examples/pose_estimation/android/app/src/androidTest/java/org/tensorflow/lite/examples/poseestimation/ml/EvaluationUtils.kt, lite/examples/pose_estimation/android/app/src/androidTest/java/org/tensorflow/lite/examples/poseestimation/ml/MovenetLightningTest.kt, lite/examples/pose_estimation/android/app/src/androidTest/java/org/tensorflow/lite/examples/poseestimation/ml/MovenetThunderTest.kt, lite/examples/pose_estimation/android/app/src/androidTest/java/org/tensorflow/lite/examples/poseestimation/ml/PoseClassifierTest.kt, lite/examples/pose_estimation/android/app/src/androidTest/java/org/tensorflow/lite/examples/poseestimation/ml/PosenetTest.kt, lite/examples/pose_estimation/android/app/src/androidTest/java/org/tensorflow/lite/examples/poseestimation/ml/VisualizationTest.kt, lite/examples/pose_estimation/android/app/src/androidTest/java/org/tensorflow/lite/examples/poseestimation/tracker/BoundingBoxTrackerTest.kt, lite/examples/pose_estimation/android/app/src/androidTest/java/org/tensorflow/lite/examples/poseestimation/tracker/KeyPointsTrackerTest.kt, lite/examples/pose_estimation/android/app/src/main/java/org/tensorflow/lite/examples/poseestimation/camera/CameraSource.kt, lite/examples/pose_estimation/android/app/src/main/java/org/tensorflow/lite/examples/poseestimation/data/Person.kt, lite/examples/pose_estimation/android/app/src/main/java/org/tensorflow/lite/examples/poseestimation/ml/MoveNet.kt, lite/examples/pose_estimation/android/app/src/main/java/org/tensorflow/lite/examples/poseestimation/ml/PoseDetector.kt, lite/examples/pose_estimation/android/app/src/main/java/org/tensorflow/lite/examples/poseestimation/ml/PoseNet.kt, lite/examples/pose_estimation/android/app/src/main/java/org/tensorflow/lite/examples/poseestimation/tracker/AbstractTracker.kt, lite/examples/pose_estimation/android/app/src/main/java/org/tensorflow/lite/examples/poseestimation/tracker/BoundingBoxTracker.kt, lite/examples/pose_estimation/android/app/src/main/java/org/tensorflow/lite/examples/poseestimation/tracker/KeyPointsTracker.kt, lite/examples/pose_estimation/android/app/src/main/java/org/tensorflow/lite/examples/poseestimation/tracker/Track.kt, lite/examples/pose_estimation/android/app/src/main/java/org/tensorflow/lite/examples/poseestimation/tracker/TrackerConfig.kt, tensorflow_examples/lite/model_maker/core/data_util/image_dataloader_test.py
This pull request adds some code to support Multipose model in the Android pose estimation app:
* Changed the data class Person to add parameters related to Multipose model.
* Update the signature of PoseDetector and its implementation classes to support Multipose model.
* Added BoundingBox tracker and KeyPoint tracker to support tracking poses across frames.
=> Updated Android pose estimation data classes to support Multipose models and add tracker logic
